### ISSUE TITLE
[1.16.4] Server Crash when using the book

### ISSUE THREAD

**Issue by NillerMedDild** [MintTeaTx/Tome-of-Blood#1]
I cheated in a Tome of Blood, created a Projectile Harm spell, saved and cast it. Immediate server crash. I had no LP at this time.

[Crash-report](https://gist.github.com/NillerMedDild/05e4d055e86e6400acc762daddd1233d)

###
- 1.16.4-1.0.2

**Comment by jurjen909** [comment]
I am running into the same problem. I made the Tome of Blood (without working on Ars Noveau before) and made a Projectile harm spell and used it with a lot of LP in my orbs and it crashed the server. I even tried to make the spell in a normal T1 tome and that worked. But when using the Tome of Blood again it crashes the server.
The error I get is the same as stated in the Crash report from @NillerMedDild 

Mod Versions:
- BloodMagic-1.16.3-3.0.5-10
- ars_nouveau-1.16.4-1.10.6
- tomeofblood-1.16.4-1.0.2

**Comment by MintTeaTx** [comment]
Ack!  Small typo, I'll fix this soon!!

**Comment by MintTeaTx** [comment]
Should be fixed on the latest release on curseforge, thanks for letting me know!
