### ISSUE TITLE
[1.16.5] Incorrect label for an item in the book "Sanguine Scientiem"

### ISSUE THREAD

**Issue by Maarzaa** [MintTeaTx/Tome-of-Blood#17]
#### Issue Description:
Incorrect label for an item in the book "Sanguine Scientiem".

#### What happens:
Label for Sacrifical Knife shows "The Blood Altar" text ([image link](https://ibb.co/4JFn5mM)). Link works correctly and goes to the page about "Sacrifical Knife".

#### What you expected to happen:
Label should show "Sacrifical Knife" text.

#### Steps to reproduce:

1. Open book "Sanguine Scientiem".
2. On the welcome page use link "Click HERE to get started." to go to the "Tiers & Getting Started" chapter.
3. On the right page mouse hover on the "Sacrifical Knife" link.
____
#### Affected Versions:

- Ars Nouveau: 1.16.5-1.24.20
- BloodMagic: 1.16.4-3.1.7-27
- Tome of Blood: 1.16.5-1.2.3
- Minecraft: 1.16.5
- Forge: 36.2.20

**Comment by starluneaux** [comment]
yeah this is a blood magic problem, Tome of Blood doesn't do this
