### ISSUE TITLE
[1.16.4-1.0.4] Infinite Mana bug

### ISSUE THREAD

**Issue by Demonpriest** [MintTeaTx/Tome-of-Blood#3]
After updateing to 1.0.4, when using a normal ars archmage spellbook, im not consuming mana anymore, resulting in infinite mana.

**Comment by MintTeaTx** [comment]
Fixed this in: commit https://github.com/MintTeaTx/Tome-of-Blood/commit/c0e6e392b4b869c00685a5670d095a4aae78ff1e

Should be good to go!
