### ISSUE TITLE
[1.16.4-1.0.5] Not enough mana bug

### ISSUE THREAD

**Issue by Demonpriest** [MintTeaTx/Tome-of-Blood#4]
When casting a spell with the tome of blood, while not having enough Ars-mana, results in the message "not enough mana" and no spell being cast. 
Found out by casting some spells with the ars book, switching to the tome, and trying to cast a spell with that.

**Comment by MintTeaTx** [comment]
What a neat issue, I'll look into it!  Shouldn't be too bad to fix.  I might have run into it last night testing a new feature

**Comment by MintTeaTx** [comment]
Yikes!  This one was fixed a while ago, closing it out now.
