### ISSUE TITLE
(Question) What does HEX do in Ars Nouveau?

### ISSUE THREAD

**Issue by minecraftDigi101** [MintTeaTx/Tome-of-Blood#5]
there was a rune that says "hex" and I have no idea what it does. could someone tell me please?

**Comment by MintTeaTx** [comment]
I didn't add Hex, that's something in base Ars Nouveau that was added, should be in the Worn Notebook

**Comment by Aresiel** [comment]
From the Worn Notebook

> Applies the Hex effect up to level 5. Hex increases any damage taken by a small amount while the user is afflicted by poison, wither, or fire. Additionally, Hex cuts the rate of Mana Regeneration and healing in half.
